### ISSUE TITLE
Mówie do ciebie rzecz

### ISSUE THREAD

**Issue by ag1zywert** [miriamkaminska/tipn_zad-kaminska#1]
Co to za szkalowanie Marvela Pani Miriam?
Tak czy siak jak zostałam bardzo rozbawiona, ale niestety nie mam mocy zaliczenia tego przedmiotu.

`może mam chociaż moc zaliczenia czegoś innego :>`

**BUZIOLE** :*

**Comment by miriamkaminska** [comment]
Bo to nawiązuje do sytuacji z zajęć, na których Pani nie było Pani Agato ://///

**Comment by ag1zywert** [comment]
Nie wiem jak się do tego odnieść ://////////////
Marvel jest cudowny.
Ale pani poczucie humoru jest lepsze. 

JESTEM FANKOM

**Comment by miriamkaminska** [comment]
Dziękuje za miłe słowa. 
Z niecierpliwością czekam na jakiegoś crossa.
Pozdrawiam.

**Comment by ag1zywert** [comment]
Spoko colabo już w przyszłym semestrze

**Comment by miriamkaminska** [comment]
ok, jak nie spadnie mi jakość życia po sesji letniej  to się odezwę
